"""Update schema

Revision ID: 365f48e858f9
Revises: 2bf7c8c7869b
Create Date: 2026-05-22 23:01:45.916626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365f48e858f9'
down_revision: Union[str, Sequence[str], None] = '2bf7c8c7869b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('privacy_mode', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'privacy_mode')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'is_2fa_enabled')
    # ### end Alembic commands ###
